# Generated by Django 4.2.2 on 2023-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0002_userprofile_delete_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuTypeCode',
            field=models.CharField(max_length=100),
        ),
    ]
