# Generated by Django 4.2.2 on 2023-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0003_alter_menu_menutypecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredient',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='salty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='spicy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='sweet',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='vegetarian',
            field=models.IntegerField(default=0),
        ),
    ]
