# Generated by Django 3.2.6 on 2023-08-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0004_menu_ingredient_menu_salty_menu_spicy_menu_sweet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='ingredient',
            new_name='main_ingredient',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='menuTypeCode',
        ),
        migrations.AddField(
            model_name='menu',
            name='hindu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='islam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='origin',
            field=models.CharField(max_length=100),
        ),
    ]
