# Generated by Django 3.2.6 on 2023-08-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0005_auto_20230816_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menuName_en',
        ),
        migrations.AddField(
            model_name='menu',
            name='menuName_en1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='menu',
            name='menuName_en2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
