# Generated by Django 3.2.6 on 2023-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0007_alter_menu_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='log',
        ),
        migrations.AddField(
            model_name='menu',
            name='food_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
