# Generated by Django 3.2.6 on 2023-08-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0008_auto_20230822_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hindu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='islam',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='salty',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='spicy',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sweet',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vegetarian',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='disliked_food',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disliked_food',
            field=models.ManyToManyField(related_name='disliked_food', to='foodifyapp.Menu'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_food',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_food',
            field=models.ManyToManyField(related_name='liked_food', to='foodifyapp.Menu'),
        ),
    ]
