# Generated by Django 3.2.6 on 2023-08-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0009_auto_20230822_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hindu',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='islam',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vegetarian',
            field=models.IntegerField(default=0),
        ),
    ]
