# Generated by Django 3.2.6 on 2023-09-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0010_auto_20230822_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menuName_en2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='salty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='spicy',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='sweet',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='disliked_food',
            field=models.ManyToManyField(blank=True, null=True, related_name='disliked_food', to='foodifyapp.Menu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_food',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_food', to='foodifyapp.Menu'),
        ),
    ]
