# Generated by Django 3.2.6 on 2023-09-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0011_auto_20230903_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='disliked_food',
            field=models.ManyToManyField(blank=True, related_name='disliked_food', to='foodifyapp.Menu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_food',
            field=models.ManyToManyField(blank=True, related_name='liked_food', to='foodifyapp.Menu'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='salty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='spicy',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sweet',
            field=models.FloatField(default=0),
        ),
    ]
