# Generated by Django 3.2.19 on 2023-09-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0012_auto_20230903_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Asian',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Chinese',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Japanese',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Korean',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Western',
            field=models.FloatField(default=0),
        ),
    ]
