# Generated by Django 4.2.5 on 2023-10-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0014_auto_20230926_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
