# Generated by Django 4.2.5 on 2023-10-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0015_remove_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.TextField(blank=True, default='No_username'),
        ),
    ]
