# Generated by Django 4.2.5 on 2023-10-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0016_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, default='No category yet', max_length=100),
        ),
    ]
