# Generated by Django 4.2.5 on 2023-10-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodifyapp', '0017_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menuType_big',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
